### ISSUE TITLE
Use new io.paketo.stacks.tiny ID to indicate "tiny"

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/go-mod#50]
We have a reference to the "tiny" stack in our codebase [here](https://github.com/paketo-buildpacks/go-mod/blob/79c30b4f0aa58ae4157faafb5fec08dea95a34aa/mod/mod.go#L193). The stack ID is changing from `org.cloudfoundry.stacks.tiny` to `io.paketo.stacks.tiny` as can be seen in https://github.com/paketo-buildpacks/go-mod/pull/49. At some point in the future, the old "tiny" stack ID will be removed. By that point we will need to be referencing the new ID.

**Comment by martyspiewak** [comment]
The goal of PR #49 was to be able to support both tiny stack ID's for a short period of time, so as not to break anyone. Unfortunately, though, the `io.paketo.stacks.tiny` id cannot be used right now because of [this reference](https://github.com/paketo-buildpacks/go-mod/blob/79c30b4f0aa58ae4157faafb5fec08dea95a34aa/mod/mod.go#L193) to the old stack.

It seems like the only way to truly be able to support both stack ID's would be for that line to somehow set both tiny stack ID's. Is that possible?

If not, I'm not sure if there is a way we can actually support both stack ID's simultaneously.

**Comment by ryanmoran** [comment]
@martyspiewak ok. So, if I'm understanding this correctly now, when you asked that this line change in the prior PR, you meant that we should support checking for both "tiny" stack IDs, not to switch to the new ID, is that right?

**Comment by martyspiewak** [comment]
@ryanmoran That wasn't what I meant originally because I didn't realize the issue of supporting both stack ID's simultaneously, but now yes that is what I think needs to happen.
